# rule identifiers to exclude from running
disabled_rules:
# Rules to be included one at a time. Remove the line to include it
  - todo
  - file_length
  - type_body_length
  - multiple_closures_with_trailing_closure
  - function_parameter_count
  - function_body_length
  - force_try
  - force_cast
  - unused_optional_binding
  - identifier_name

# opt-in only rules
# Rules commented needs to be included one at a time. Remove the # to include it
opt_in_rules: 
  - closure_end_indentation
  - closure_spacing
  - colon
  - comma
  - control_statement
  - empty_count
  - overridden_super_call
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - yoda_condition

# paths to include during linting. `--path` is ignored if present.
included: 
  - AppForBudget

# paths to ignore during linting. Takes precedence over `included`.
excluded: 
  - Pods

# Rules run by `swiftlint analyze` (experimental)
analyzer_rules: 
  - explicit_self

# Rules customizations:
# configurable rules can be customized from this configuration file
# binary rules can set their severity level

line_length:
    warning: 160
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_interpolated_strings: true
    ignores_urls: true

large_tuple: 
   warning: 3
   error: 4


type_name:
  min_length: 4 # only warning
  max_length:
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names

identifier_name:
  min_length: # only min_length
    error: 2 # only error

#function_body_length:
#  warning: 50 # default is 40

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
